version: "3.9"
services:
  gateway:
    build: 
      context: ./kvlgateway
      dockerfile: Dockerfile
    ports:
      - "7001:7001"

  registry:
    build: 
      context: ./kvlregistry
      dockerfile: Dockerfile
    ports:
      - "6001:6001"
    depends_on:
      - gateway

  node1:
    build: 
      context: ./kvlnode
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on: 
      - registry
  node2:
    build: 
      context: ./kvlnode
      dockerfile: Dockerfile
    ports:
      - "5002:5001"
    depends_on: 
      - registry
  
