version: "3.9"
services:
  registry:
    build: 
      context: ./kvlregistry
      dockerfile: Dockerfile
    ports:
      - "6001:6001"
  node1:
    build: 
      context: ./kvlnode
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on: 
      - registry
  gateway:
    build: 
      context: ./kvlgateway
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
    depends_on: 
      - node1
  
